url: 'http://localhost:8082'

mongodb:
  server:   192.168.1.98
  database: uptime
  user:     uptime
  password: uptime
  connectionString:       # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: false

plugins:
  - ./plugins/console
  #- ./plugins/patternMatcher
  - ./plugins/resultVerify
  - ./plugins/httpOptions
  - ./plugins/email
  - ./plugins/phone
  # - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    #service:    # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    host: "smtp.knight.com"
    port: 25
    secure: false
    auth:
      user:   "tianyekuo@knight.com"       # The email account username, e.g. 'username@gmail.com'
      pass:   "password"       # The email account password, e.G. 'password'
  event:
    up:        false
    down:      true
    paused:    false
    restarted: false
  message:
    from:   tianyekuo@knight.com         
    to:     dev@knight.com,qa@knight.com  
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

phone:
  number:

basicAuth:
  username:    admin
  password:    password
verbose: true # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions: 
